image: docker:latest
services:
  - docker:dind

variables:
  REGISTRY: registry.vshn.net
  KUBECONFIG: /tmp/kube
  OC_VERSION: v3.9
  OPENSHIFT_PROJECT: vshn-signalilo-prod
  OPENSHIFT_TOKEN: $KUBE_TOKEN
  OPENSHIFT_URL: $KUBE_URL

.dockerbuild: &dockerbuild
  before_script:
    - docker info
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $REGISTRY
  script:
    - docker pull ${REGISTRY}/${CI_PROJECT_PATH}:builder || true
    - docker build --target builder --cache-from ${REGISTRY}/${CI_PROJECT_PATH}:builder --tag ${REGISTRY}/${CI_PROJECT_PATH}:builder .
    - docker build --cache-from ${REGISTRY}/${CI_PROJECT_PATH}:builder --tag ${REGISTRY}/${CI_PROJECT_PATH}:${IMAGE_TAG} .
    - docker push ${REGISTRY}/${CI_PROJECT_PATH}:builder
    - docker push ${REGISTRY}/${CI_PROJECT_PATH}:${IMAGE_TAG}
  tags:
    - dockerbuild

.openshift: &openshift
  image: docker.io/appuio/oc:$OC_VERSION
  before_script:
    - oc login $OPENSHIFT_URL --token=$OPENSHIFT_TOKEN
  script:
    - oc -n $OPENSHIFT_PROJECT process -f deploy/openshift-template.yaml --local
        -p APP_IMAGE=${REGISTRY}/${CI_PROJECT_PATH}:${IMAGE_TAG}
        -p APP_STAGE=$APP_STAGE
        -p CI_ENVIRONMENT_SLUG=$CI_ENVIRONMENT_SLUG
        -p CI_PROJECT_PATH_SLUG=$CI_PROJECT_PATH_SLUG
        -p CI_COMMIT_SHA=$CI_COMMIT_SHA
        -p OPENSHIFT_PROJECT=$OPENSHIFT_PROJECT
        -p TLS_ACME=$TLS_ACME
        -p URL=$URL
        | oc -n $OPENSHIFT_PROJECT apply --overwrite -f -
  tags:
    - dockerbuild

build:dev:
  stage: build
  variables:
    IMAGE_TAG: dev
  <<: *dockerbuild
  tags:
    - dockerbuild
  only:
    - dev

build:latest:
  stage: build
  variables:
    IMAGE_TAG: latest
  <<: *dockerbuild
  only:
    - master

build:tag:
  stage: build
  variables:
    IMAGE_TAG: ${CI_COMMIT_TAG}
  <<: *dockerbuild
  only:
    - tags

deploy:dev:
  <<: *openshift
  stage: deploy
  variables:
    APP_STAGE: dev
    IMAGE_TAG: dev
    TLS_ACME: "false"
    URL: vshn-signalilo-dev.appuioapp.ch
  environment:
    name: review/dev
    url: https://${URL}/
    on_stop: deploy:stop
  only:
    - dev

deploy:production:
  <<: *openshift
  stage: deploy
  when: manual
  variables:
    APP_STAGE: prod
    IMAGE_TAG: $CI_COMMIT_TAG
    TLS_ACME: "true"
    URL: signalilo.vshn.net
  environment:
    name: production
  only:
    - tags

deploy:stop:
  <<: *openshift
  stage: deploy
  when: manual
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/dev
    action: stop
  script:
    - oc -n $OPENSHIFT_PROJECT delete all -l app="$CI_ENVIRONMENT_SLUG"
