name: Build & Push Container Image
on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/${{ github.repository }}
      QUAY_IMAGE: quay.io/${{ github.repository }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Set version latest
      if: github.ref == 'refs/heads/master'
      run: echo "VERSION=latest" >> ${GITHUB_ENV}
    - name: Set version from tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> ${GITHUB_ENV}
    - name: Set binary version from Git
      run: echo "BINARY_VERSION=$(git describe --tags --always --dirty --match=v*)" >> ${GITHUB_ENV}
    - name: Build Image
      run: make docker
      env:
        IMAGE_NAME: "${IMAGE}:${VERSION}"
    - name: Push Image to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login docker.io --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
        docker push "${IMAGE}:${VERSION}"
    - name: Push Image to Quay
      env:
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      run: |
        docker login quay.io --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
        docker tag "${IMAGE}:${VERSION}" ${QUAY_IMAGE}:${VERSION}
        docker push "${QUAY_IMAGE}:${VERSION}"
